### ISSUE TITLE
Error during smart home setup

### ISSUE THREAD

**Issue by Leemo94** [airalab/robonomics-smarthome#3]
Encountering the following error after setting up the Smart Home setup. Two isolated setups encounter the same issue (Leemo/Cybersapien)

Error
```
ubuntu@ubuntu:~$ journalctl -u home-assistant@homeassistant.service -f
-- Journal begins at Mon 2021-12-06 13:58:40 UTC. --
Jan 14 14:50:00 ubuntu hass[2546]: asyncio.exceptions.CancelledError
Jan 14 14:50:00 ubuntu hass[2546]: The above exception was the direct cause of the following exception:
Jan 14 14:50:00 ubuntu hass[2546]: Traceback (most recent call last):
Jan 14 14:50:00 ubuntu hass[2546]:   File "/srv/homeassistant/lib/python3.9/site-packages/homeassistant/components/shell_command/init.py", line 83, in async_service_handler
Jan 14 14:50:00 ubuntu hass[2546]:     stdout_data, stderr_data = await asyncio.wait_for(
Jan 14 14:50:00 ubuntu hass[2546]:   File "/usr/lib/python3.9/asyncio/tasks.py", line 494, in wait_for
Jan 14 14:50:00 ubuntu hass[2546]:     raise exceptions.TimeoutError() from exc
Jan 14 14:50:00 ubuntu hass[2546]: asyncio.exceptions.TimeoutError
Jan 14 14:50:01 ubuntu hass[2546]: 2022-01-14 14:50:01 ERROR (MainThread) [homeassistant.components.shell_command] Error running command: python3 python_scripts/send_datalog.py sensor_humidity={{ states("sensor.humidity_lumi_158d0007bc158c") }} sensor_temp={{ states("sensor.temperature_lumi_158d0007bc158c") }} sensor_pressure={{ states("sensor.pressure_lumi_158d0007bc158c") }}, return code: 1
Jan 14 14:50:01 ubuntu hass[2546]: NoneType: None
```
Config
```
automation:
  - alias: "send_datalog_aqara_sensor" 
    trigger:
      platform: time_pattern
      minutes: "/5"

    action:
      service: shell_command.send_datalog_aqara_sensor

shell_command:
  send_datalog_aqara_sensor: 'python3 python_scripts/send_datalog.py sensor_humidity={{ states("sensor.humidity_lumi_158d0007bc158c") }} sensor_temp={{ states("sensor.temperature_lumi_158d0007bc158c") }} sensor_pressure={{ states("sensor.pressure_lumi_158d0007bc158c") }}' 
```

**Comment by Leemo94** [comment]
Resolved by editing utils.py with new endpoint url:
```
nano /srv/homeassistant/python_scripts/utils.py
```
```
def connect_robonomics() -> SubstrateInterface:
    substrate = SubstrateInterface(
            url="wss://kusama.rpc.robonomics.network",
            ss58_format=32,
            type_registry_preset="substrate-node-template",
            type_registry= {
                "types": {
                    "Record": "Vec<u8>",
                    "Parameter": "Bool",
                    "LaunchParameter": "Bool",
                    "<T as frame_system::Config>::AccountId": "AccountId",
                    "RingBufferItem": {
                        "type": "struct",
                        "type_mapping": [["timestamp", "Compact<u64>"], ["payload", "Vec<u8>"]],
                    },
                    "RingBufferIndex": {
                        "type": "struct",
                        "type_mapping": [["start", "Compact<u64>"], ["end", "Compact<u64>"]],
                    },
                }
            }
            )
    return substrate
```
